---
title: "first_analysis"
author: "Gabe Cederberg"
date: "3/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading the important packages for the exam.

library(tidyverse)
library(dplyr)
library(readr)
library(fivethirtyeight)
library(janitor)
library(ggthemes)
library(gt)
library(reprex)
library(magrittr)
library(stringr)
library(haven)
library(infer)
library(readxl)
library(viridis) 
library(lubridate)
library(tidyr)
library(broom)
library(utils)
library(gganimate)

```

# {.tabset}

## COVID 19 Analysis

```{r, echo = FALSE, message = FALSE, warning = FALSE}

# Loading data

import <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") 

import$dateRep <- 
  as.Date(import$dateRep, "%d/%m/%Y")

clean_import <- import %>% 
  select(date = "dateRep",
         day:year,
         new_cases = "cases",
         new_deaths = "deaths",
         country = "countriesAndTerritories",
         geoid = "geoId",
         code = "countryterritoryCode",
         pop_2018 = "popData2018")

other_data <- read_excel("raw-data/OtherData.xlsx")

merged_data <- clean_import %>% 
  left_join(other_data) %>% 
  select(date:pop_2018,
         gdp_2018 = "GDP (constant 2010 US$) 2018",
         health_exp_gdp_2016 = "Current health expenditure (% of GDP) 2016",
         out_pocket_exp_2016 = "Out-of-pocket expenditure (% of current health expenditure) 2016",
         private_exp_pp_2016 = "Domestic private health expenditure per capita (current US$) 2016",
         gini_2017 = "GINI index (World Bank estimate) 2017") %>% 
  mutate(pop_millions = pop_2018 / 1000000,
         gdp_billions = gdp_2018 / 1000000000) %>% 
  select(date:code, 
         health_exp_gdp_2016:gdp_billions) %>% 
  mutate(latin_america = ifelse(
            country == "Brazil" |
            country == "Mexico" |
            country == "Colombia" |
            country == "Argentina" |
            country == "Venezuela" |
            country == "Peru" |
            country == "Chile" | 
            country == "Ecuador" |
            country == "Guatemala" |
            country == "Cuba" |
            country == "Bolivia" |
            country == "Dominican_Republic" |
            country == "Haiti" |
            country == "Honduras" |
            country == "Paraguay" |
            country == "El_Salvador" |
            country == "Nicaragua" |
            country == "Costa_Rica" |
            country == "Puerto_Rico" |
            country == "Panama" |
            country == "Uruguay", 1, 0),
         south_america = ifelse(
            country == "Brazil" |
            country == "Colombia" |
            country == "Argentina" |
            country == "Venezuela" |
            country == "Peru" |
            country == "Chile" | 
            country == "Ecuador" |
            country == "Bolivia" |
            country == "Paraguay" |
            country == "Uruguay", 1, 0)) %>% 
  group_by(country) %>% 
  arrange(date) %>% 
  mutate(running_sum = cumsum(new_cases)) %>% 
  ungroup() %>% 
  mutate(cases_pop = (new_cases / pop_millions),
         deaths_pop = (new_deaths / pop_millions),
     #    deaths_cases = deaths_pop / cases_pop,
         running_sum_pop = running_sum / pop_millions) %>% 
  arrange(country)

```


```{r, echo = FALSE, message = FALSE}
# Writing function

days_since <- function(x){
rows <- merged_data %>% 
  filter(country == x) %>% 
  select(country, date, running_sum) %>% 
  filter(running_sum >= 100) %>%
  nrow()

merged_data %>% 
  filter(country == x) %>% 
  select(country, date, running_sum) %>% 
  filter(running_sum >= 100) %>%
  mutate(days_since_100 = 1:rows)
}

countries_included <- c("Brazil", 
       "Mexico", 
       "Colombia", 
       "Argentina", 
       "Venezuela", 
       "Peru", 
       "Chile", 
       "Ecuador", 
#       "Guatemala", 
       "Cuba", 
       "Bolivia", 
       "Dominican_Republic", 
#       "Haiti", 
       "Honduras", 
       "Paraguay", 
       "El_Salvador", 
 #      "Nicaragua", 
       "Costa_Rica", 
       "Puerto_Rico", 
       "Panama", 
       "Uruguay")

test <- map_df(countries_included, ~ days_since(.))

ggplot(test, aes(days_since_100, running_sum, color = country)) +
  geom_line() +
    theme_classic() +
  labs(
    title = "Total Cases",
    subtitle = "Brazil's cases have grown faster than in any other Latin American Country",
       y = "Cases",
       x = "Days Since 100 Confirmed Cases",
    caption = "Data from the European Union's European Centre for Disease Prevention and Control",
    color = "Country") +
  theme(legend.position = "bottom") +
    transition_reveal(date)
#  scale_color_viridis_d(option = "plasma")


```

```{r, echo = FALSE}
a <- merged_data %>% 
  filter(date > "2020-03-14",
         south_america == 1 )

merged_data %>% 
  filter(date == "2020-04-28" &
         latin_america == 1) %>% 
  arrange(desc(running_sum)) %>% 
  select(country, running_sum) %>% 
  gt() %>% 
  tab_header(
     title = "Cases by Country on April 29th",
     subtitle = "Data from the European Union's European Centre for Disease Prevention and Control") %>% 
  cols_label(country = "Country",
             running_sum = "Total Cases") %>% 
  cols_align(align = c("center"), columns = TRUE)

merged_data %>% 
  filter(date == "2020-04-28" &
         latin_america == 1) %>% 
  arrange(desc(cases_pop)) %>% 
  select(country, cases_pop) %>%
  head(10) %>% 
  gt() %>% 
  tab_header(
     title = "Cases per Capita by Country on April 29th",
     subtitle = "Data from the European Union's European Centre for Disease Prevention and Control") %>% 
  cols_label(country = "Country",
             cases_pop = "Cases Per Capita") %>% 
  cols_align(align = c("center"), columns = TRUE)
```


```{r, echo = FALSE}
# Daily new cases 

ggplot(a, aes(x = date, y = new_cases, color = country)) +
  geom_line() +
  theme_classic() +
  labs(
    title = "New Daily Cases by Country",
    subtitle = "Cases Rapidly Increasing After Mid-March",
       y = "New Daily Cases",
       x = "",
    caption = "Data from the European Union's European Centre for Disease Prevention and Control",
    color = "Country") +
  theme(legend.position = "bottom")  +
    transition_reveal(date)
#   + scale_color_viridis(discrete = TRUE, option = "C")
  
```

```{r, echo = FALSE}
# Cumulative cases 

ggplot(a, aes(x = date, y = running_sum, color = country)) +
  geom_line() +
  theme_classic() +
  labs(
    title = "Cumulative Cases by Country",
    subtitle = "Cases Rapidly Increasing After Mid-March",
       y = "Total Cases",
       x = "",
    caption = "Data from the European Union's European Centre for Disease Prevention and Control",
    color = "Country") +
  theme(legend.position = "bottom")  +
    transition_reveal(date)
#   + scale_color_viridis(discrete = TRUE, option = "C")
  
```

## Combined Data Analysis

```{r, echo = FALSE, warning = FALSE}
b <- merged_data %>% 
  filter(date == "2020-04-28" &
         latin_america == 1)
```

```{r, echo = FALSE, warning = FALSE}
summary(lm(running_sum ~ gini_2017 + pop_millions + gdp_billions + health_exp_gdp_2016 + out_pocket_exp_2016 + private_exp_pp_2016, data = b))
```

```{r, echo = FALSE, warning = FALSE}
summary(lm(scale(running_sum) ~ scale(gini_2017) + scale(pop_millions) + scale(gdp_billions) + scale(health_exp_gdp_2016) + scale(out_pocket_exp_2016) + scale(private_exp_pp_2016), data = b)) 
```

```{r, echo = FALSE, warning = FALSE}
ggplot(b, aes(x = out_pocket_exp_2016, y = running_sum, color = country)) +
  geom_point(size = 2.5) +
  theme_classic() +
  labs(
    title = "Cumulative Cases by Out of Pocket Health Expenditure in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "Out-of-pocket expenditure as a % of current health expenditure in 2016",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position = "bottom") 
```

```{r, echo = FALSE, warning = FALSE}
ggplot(b, aes(x = out_pocket_exp_2016, y = running_sum, color = country)) +
  geom_point(size = 2.5) +
  geom_smooth() +
  theme_classic() +
  labs(
    title = "Cumulative Cases by Out of Pocket Health Expenditure in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "Out-of-pocket expenditure as a % of current health expenditure in 2016",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position = "bottom") 
```

```{r, echo = FALSE, warning = FALSE}
ggplot(b, aes(x = gdp_billions, y = running_sum, color = country)) +
  geom_point(size = 2.5) +
  theme_classic() +
  labs(
    title = "Cumulative Cases by GDP in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "GDP in 2018 (billions of USD)",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position = "bottom") 
```

```{r, echo = FALSE, warning = FALSE}


ggplot(b, aes(x = gdp_billions, y = running_sum)) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x) +
  theme_classic() +
  labs(
    title = "Cumulative Cases by GDP in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "GDP in 2018 (billions of USD)",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position = "bottom") 
```

```{r, echo = FALSE, warning = FALSE}
# Gini Coefficient

ggplot(b, aes(x = gini_2017, y = running_sum, color = country)) +
  geom_point() +
  theme_classic() +
  labs(
    title = "Cumulative Cases by Gini Coefficient in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "Gini Coefficient in 2017",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position="bottom") 
```

```{r, echo = FALSE, warning = FALSE}
# Gini Coefficient

ggplot(b, aes(x = gini_2017, y = running_sum)) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x) +
  theme_classic() +
  labs(
    title = "Cumulative Cases by Gini Coefficient in South America",
    subtitle = "Slight positive relationship",
       y = "Cumulative Cases on 4/28",
       x = "Gini Coefficient in 2017",
    caption = "Data from the European Union's 
    European Centre for Disease Prevention 
    and Control and the World Bank",
    color = "Country") +
  theme(legend.position="bottom")
```

