---
title: "regressions"
author: "Gabe Cederberg"
date: "5/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading the important packages for the analysis. 

library(tidyverse)
library(dplyr)
library(readr)
library(fivethirtyeight)
library(janitor)
library(ggthemes)
library(gt)
library(reprex)
library(magrittr)
library(stringr)
library(haven)
library(infer)
library(readxl)
library(viridis) 
library(lubridate)
library(tidyr)
library(broom)
library(utils)
library(gganimate)
library(stargazer)

options(scipen = 999)
```

## COVID 19 Analysis

```{r, echo = FALSE,  warning = FALSE}
# Loading data

import <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") %>% 
  filter(continentExp == "America") %>% 
  select("date" = dateRep, 
         "new_cases" = cases,
         "new_deaths" = deaths,
         "country" = countriesAndTerritories,
         "code" = countryterritoryCode,
         "pop_2018" = popData2018)

import

import$date <- as.Date(import$date, "%d/%m/%Y")

import$country <- gsub("_", " ", import$country)
```


```{r, echo = FALSE,  warning = FALSE}
wb_data <- read_excel("raw-data/wb_data.xlsx") 

```


```{r, echo = FALSE,  warning = FALSE}
test_data <- read_excel("raw-data/testing_data.xlsx") %>% 
  clean_names() %>% 
  select(country, 
         tests_per_million = "tests_per_1m_pop")
```

```{r, echo = FALSE}

shutdown_data <- read_csv("raw-data/lockdown_data.csv",
                          col_types = cols(
    Date = col_date(format = "%m/%d/%y"))) %>% 
  clean_names() %>% 
  select(country, date, type)

shutdown_data$date <- as.Date(shutdown_data$date, "%d/%m/%y")

```


```{r, echo = FALSE,  warning = FALSE}

merged <- import %>% 
  left_join(wb_data, by = c("country", "code")) %>% 
  left_join(test_data, by = "country") %>% 
  select(date:pop_2018,
         tests_per_million,
         gdp_2018 = "GDP (constant 2010 US$) 2018",
         health_exp_gdp_2016 = "Current health expenditure (% of GDP) 2016",
         out_pocket_exp_2016 = "Out-of-pocket expenditure (% of current health expenditure) 2016",
         private_exp_pp_2016 = "Domestic private health expenditure per capita (current US$) 2016",
         gini_2017 = "GINI index (World Bank estimate) 2017", 
         people_per_sq_km,
         informal_sector, 
         authoritarian) %>% 
  mutate(pop_millions = pop_2018 / 1000000,
         gdp_billions = gdp_2018 / 1000000000) %>% 
  select(date:code, 
         tests_per_million,
         health_exp_gdp_2016:gdp_billions,
         people_per_sq_km,
                  informal_sector, 
         authoritarian) %>% 
  mutate(latin_america = ifelse(
            country == "Brazil" |
            country == "Mexico" |
            country == "Colombia" |
            country == "Argentina" |
            country == "Venezuela" |
            country == "Peru" |
            country == "Chile" | 
            country == "Ecuador" |
            country == "Guatemala" |
            country == "Cuba" |
            country == "Bolivia" |
            country == "Dominican Republic" |
            country == "Haiti" |
            country == "Honduras" |
            country == "Paraguay" |
            country == "El Salvador" |
            country == "Nicaragua" |
            country == "Costa_Rica" |
            country == "Puerto Rico" |
            country == "Panama" |
            country == "Uruguay", 1, 0),
         south_america = ifelse(
            country == "Brazil" |
            country == "Colombia" |
            country == "Argentina" |
            country == "Venezuela" |
            country == "Peru" |
            country == "Chile" | 
            country == "Ecuador" |
            country == "Bolivia" |
            country == "Paraguay" |
            country == "Uruguay", 1, 0)) %>% 
  filter(latin_america == 1) %>% 
  group_by(country) %>% 
  arrange(date) %>% 
  mutate(running_cases = cumsum(new_cases),
         running_deaths = cumsum(new_deaths)) %>% 
  ungroup() %>% 
  mutate(cases_pop = (new_cases / pop_millions),
         deaths_pop = (new_deaths / pop_millions),
         running_sum_pop = running_cases / pop_millions,
         running_deaths_pop = running_deaths / pop_millions) %>% 
  arrange(country)

reg <- merged %>% 
    full_join(shutdown_data, by = "country") %>% 
    mutate(shutdown = ifelse(is.na(type), 0, 1)) %>% 
  group_by(country) %>% 
  mutate(max_cases_pop = max(running_sum_pop)) %>% 
  ungroup() %>% 
  filter(running_sum_pop == max_cases_pop)

reg %>% 
  filter(is.na(informal_sector))
```

```{r, echo = FALSE, warning = FALSE}
model_1 <- lm(running_cases ~ tests_per_million + shutdown + pop_millions + gdp_billions + health_exp_gdp_2016 + out_pocket_exp_2016 + private_exp_pp_2016 + people_per_sq_km + informal_sector + authoritarian, data = reg) 
summary(model_1)


stargazer(model_1, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Total Cases on May 5th"),
          covariate.labels = c("Tests per million",
                           "Shutdown before March 30th (1 or 0)",
                           "Population (millions)",
                           "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Authoritarian leader (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg1.html")

```

```{r, echo = FALSE, warning = FALSE}
model_2 <- lm(scale(running_cases) ~ scale(tests_per_million) + shutdown + scale(pop_millions) + scale(gdp_billions) + scale(health_exp_gdp_2016) + scale(out_pocket_exp_2016) + scale(private_exp_pp_2016) + scale(people_per_sq_km) + scale(informal_sector) + authoritarian, data = reg) 
summary(model_2)

stargazer(model_2, 
          title = "Standardized Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Total Cases on May 5th"),
          covariate.labels = c("Tests per million",
                           "Shutdown before March 30th (1 or 0)",
                           "Population (millions)",
                           "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Authoritarian leader (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg1a.html")

aa <- reg$running_cases
sd(aa)

bb <- reg$pop_millions
sd(bb)

48.213

cc <- reg$gdp_billions
sd(cc)

536.51

#pop

26396.97 * 3.80310
  
#gdp
  
26396.97 * -3.16483

```

```{r, echo = FALSE, warning = FALSE}
model_8 <- lm(running_sum_pop ~ tests_per_million + shutdown + gdp_billions + health_exp_gdp_2016 + out_pocket_exp_2016 + private_exp_pp_2016 + people_per_sq_km + informal_sector + authoritarian, data = reg) 
summary(model_8)

stargazer(model_8, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Total Cases Per Capita on May 5th"),
          covariate.labels = c("Tests per million",
                           "Shutdown before March 30th (1 or 0)",
                           "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Authoritarian leader (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg2.html")

```

```{r, echo = FALSE, warning = FALSE}
model_9 <- lm(scale(running_sum_pop) ~ scale(tests_per_million) + shutdown + scale(gdp_billions) + scale(health_exp_gdp_2016) + scale(out_pocket_exp_2016) + scale(private_exp_pp_2016) + scale(people_per_sq_km) + scale(informal_sector) + authoritarian, data = reg) 
summary(model_9)

stargazer(model_9, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Standardized Total Cases Per Capita on May 5th"),
          covariate.labels = c("Tests per million",
                           "Shutdown before March 30th (1 or 0)",
                           "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Authoritarian leader (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg2a.html")

aa <- reg$running_sum_pop
sd(aa)

ab <- reg %>% 
  filter(!is.na(informal_sector))
bb <- ab$informal_sector
sd(bb)

48.213

cc <- reg$gdp_billions
sd(cc)

536.51

#pop

670.5533 * 2.427
  
#gdp
  
670.5533 * -3.16483

ggplot(reg, aes(informal_sector, running_sum_pop, color = country)) +
  geom_point() +
  geom_abline() +
  theme_classic() +
#  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Size of Informal Sector and Cases per Capita",
       y = "Cases per capita",
       x = "% of workforce in informal sector",
    caption = "Cases as of May 5th, 2020",
    color = "") +
  theme(legend.position = "bottom")
reg

```

```{r, echo = FALSE, message = FALSE}
# Writing function

reg_2 <- merged %>% 
    full_join(shutdown_data, by = "country") %>% 
    mutate(shutdown = ifelse(is.na(type), 0, 1)) %>% 
  group_by(country) %>% 
  mutate(max_cases_pop = max(running_sum_pop)) %>% 
  ungroup()


days_since <- function(x){
rows <- reg_2 %>% 
  filter(country == x) %>% 
  select(country, date.x, running_cases) %>% 
  filter(running_cases >= 1000) %>%
  nrow()

reg_2 %>% 
  filter(country == x) %>% 
  select(country, date.x, running_cases, running_sum_pop) %>% 
  filter(running_cases >= 1000) %>%
  mutate(days_since_1000 = 1:rows)
}

# rows <- reg_2 %>% 
#   filter(country == "Brazil") %>% 
#   select(country, date.x, running_cases) %>% 
#   filter(running_cases >= 100) %>%
#   nrow()
# 
# reg_2 %>% 
#   filter(country == "Brazil") %>% 
#   select(country, date.x, running_cases) %>% 
#   filter(running_cases >= 100) %>%
#   mutate(days_since_100 = 1:rows)


countries_included <- c("Brazil", 
       "Mexico", 
       "Colombia", 
        "Argentina", 
   #     "Venezuela", 
        "Peru", 
        "Chile", 
        "Ecuador", 
  #    "Guatemala", 
        "Cuba", 
         "Bolivia", 
        "Dominican Republic", 
   #     "Haiti", 
       "Honduras", 
     #    "Paraguay", 
   #      "El Salvador", 
    #     "Nicaragua", 
      #   "Costa Rica", 
         "Puerto Rico", 
   #    "Uruguay",
           "Panama") 


days_since <- map_df(countries_included, ~ days_since(.))

combined <- days_since %>% 
    full_join(shutdown_data, by = "country") %>% 
    mutate(shutdown = ifelse(is.na(type), 0, 1)) %>% 
  group_by(country) %>% 
  mutate(max_cases = max(running_cases)) %>% 
  ungroup() %>% 
  filter(days_since_1000 == 1) %>% 
  mutate(timely = ifelse(is.na(date) | date > date.x, 0, 1))

for_graph <- days_since %>% 
    full_join(shutdown_data, by = "country") %>% 
    mutate(shutdown = ifelse(is.na(type), 0, 1)) %>% 
  group_by(country) %>% 
  mutate(max_cases = max(running_cases)) %>% 
  ungroup()

for_graph %>% 
  ggplot(aes(days_since_1000, running_cases, color = country)) + 
  geom_line() +
  theme_classic() +
#  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "Total Case Growth",
       y = "Total Cases",
       x = "Days since 1,000 confirmed cases",
    color = "") +
  theme(legend.position = "none")

model_3 <- lm(max_cases ~ timely, data = combined)
summary(model_3)


stargazer(model_3, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Total Cases on May 5th"),
          covariate.labels = c("Shutdown before 1,000 cases (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg3.html")
```


```{r}

xx <- combined %>% 
  left_join(reg, by = "country") %>% 
  mutate(running_cases_pop = max_cases / pop_millions)

xx

model_4 <- lm(running_cases_pop ~ timely + tests_per_million + gdp_billions + health_exp_gdp_2016 + out_pocket_exp_2016 + private_exp_pp_2016 + people_per_sq_km + informal_sector, data = xx)
summary(model_4)

stargazer(model_4, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Total Cases Per Capita on May 5th"),
          covariate.labels = c("Shutdown before 1,000 cases (1 or 0)",
                               "Tests per million",
                               "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg4.html")

```

```{r, message = FALSE}
model_5 <- lm(scale(running_cases_pop) ~ timely + scale(tests_per_million) + scale(gdp_billions) + scale(health_exp_gdp_2016) + scale(out_pocket_exp_2016) + scale(private_exp_pp_2016) + scale(people_per_sq_km) + scale(informal_sector), data = xx)
summary(model_5)

stargazer(model_5, 
          title = "Standardized Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Standardized Total Cases Per Capita on May 5th"),
          covariate.labels = c("Shutdown before 1,000 cases (1 or 0)",
                               "Tests per million",
                               "GDP (billions USD)",
                           "Health Expenditure as % of GDP",
                           "Out of pocket exp. as % of health exp.",
                           "Private health exp. per capita (USD)",
                           "People per square km",
                           "% of workforce in informal sector",
                           "Constant"),
          type = 'html', 
          out = "reg_output/reg5.html")
xa <- xx %>% 
  filter(country != "Puerto Rico")

xa %>% 
  ggplot(aes(tests_per_million, running_cases_pop)) + 
  geom_point() +
  geom_smooth() +
  theme_classic() +
#  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "COVID-19 Testing and COVID-19 Cases",
       y = "Total cases per million",
       x = "Tests per million",
    color = "") +
  theme(legend.position = "none")
```

```{r, message = FALSE}
xa %>% 
  ggplot(aes(gdp_billions, running_cases_pop)) + 
  geom_point() +
  geom_smooth() +
  theme_classic() +
#  scale_color_viridis_d(option = "plasma") +
  labs(
    title = "GDP and COVID-19 Cases",
       y = "Total cases per million",
       x = "GDP (Billions of US Dollars)",
    color = "") +
  theme(legend.position = "none")
```

